apiVersion: 1
deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: vm
    type: prometheus
    access: proxy
    orgId: 1
    url: http://victoria_metrics:8428
    isDefault: true
    version: 1
    editable: true
